#!/bin/bash
# File              : dmenu_mager
# License           : MIT License
# Author            : M. Nabil Adani <nblid48@gmail.com>
# Date              : Jumat, 15/05/2020 13:12 WIB
# Last Modified Date: Minggu, 11/10/2020 12:44 WIB
# Last Modified By  : M. Nabil Adani <nblid48@gmail.com>
{ pkgs }:
pkgs.writeShellScriptBin "dmenu-mager" ''
  DMENU="rofi -dmenu -i -p 󱊒 "
  # OPTIONS = [[label, command]]
  OPTIONS=''''
  [
    [ "droidcam",               "droidcam-rofi" ],
    [ "play video0",            "mpv --no-audio --window-scale=0.5 av://v4l2:/dev/video0 --vf=hflip --profile=low-latency --untimed" ],
    [ "play video1",            "mpv --no-audio --window-scale=0.5 av://v4l2:/dev/video1 --vf=hflip --profile=low-latency --untimed" ],
    [ "play video2",            "mpv --no-audio --window-scale=0.5 av://v4l2:/dev/video2 --vf=hflip --profile=low-latency --untimed" ],
    [ "Mirror HP",              "adb-scrcpy" ],
    [ "Wifi Menu",              "rofi-network-manager" ],
    [ "Postgres Manager",       "pgs-manager"],
    [ "Music",                  "dmenu_mpc" ],
    [ "Change Wallpaper",       "wallsetter" ],
    [ "Notes txt",       "note" ],
    [ "Notes From Clip",       "note-from-clipboard" ],
    [ "Rofi-Wallpaper",         "rofi-wall"],
    [ "Rofi-Youtube",         "rofi-yt"],
    [ "Rofi-Rclone",         "rofi-clone"],
    [ "Rofi-netspeed",         "rofi-net"],
    [ "Rofi-music",             "rofi-beats" ],
    [ "Rofi-screnshoot",         "rofi-screenshot" ],
    [ "Rofi-Notes",             "rofi-notes" ],
    [ "Rofi-keybinds",          "keybinds" ],
    [ "Rofi-wlstream",          "rofi-wlstream" ],
    [ "Rofi-Filemanager",          "rofi-filemanager" ],
    ["dm-dictionary",     "dm-dictionary"],
    ["dm-ip",     "dm-ip"],
    ["dm-man",     "dm-man"],
    ["dm-pipewire-switch",     "dm-audiout"],
    ["dm-usbmount",     "dm-usbmount"],
    ["dm-weather",     "dm-weather"],
    ["dm-kill",     "dm-kill"],
    [ "Rofi-dict",              "rofi-dict" ],
    [ "Rofi-aria",              "rofi-aria" ],
    [ "Rofi-calc",              "rofi-calcx" ],
    [ "Rofi-zotero",            "rofi-zotero" ],
    [ "Rofi-systemd",           "rofi-systemd" ],
    [ "toggle-blur",           "toggle-blur" ],
    [ "toggle-opacity",           "toggle-opacity" ],
    [ "kill droidcam",          "pkill droidcam-cli" ],
    [ "monitor",                "monitor-projection" ],
    [ "Display monitor",        "python3 /home/nandar/hyprnix/config/scripts/monitor_display.py" ],
    [ "Lumi Education",        "appimage-run /home/nandar/App/Lumi-0.10.0.AppImage" ],
    [ "Fet Scheduler",        "appimage-run /home/nandar/App/fet-6.25.0-x86_64.AppImage" ],
    [ "Virtual Monitor",        "virtmon" ],
    [ "VOS Viewer",             "java -jar /home/nandar/App/VOSviewer.jar" ],
    [ "Stop VPN",               "systemctl stop wg-quick-wg0" ],
    [ "Star VPN",               "systemctl start wg-quick-wg0" ],
    [ "Start Screen to Vcam ",  "wl-screenrec --ffmpeg-muxer v4l2 -f /dev/video0" ],
    [ "Stop Screen to Vcam ",   "pkill wl-screenrec" ],
    [ "translate-input",        "dmenu_translate -i" ],
    [ "Start Cloudflared",      "cloudflared tunnel run moodle" ],
    [ "Stop Cloudflared",       "pkill cloudflared" ],
    [ "photopea",               " brave --new-window --app=https://photopea.com/" ],
    [ "Chat GPT",               " brave --app=https://chat.openai.com/" ],
    [ "MMBC Travel",               " brave --app=https://transaksi.klikmbc.biz/" ],
    [ "Google Drive",           " brave --app=https://drive.google.com/" ],
    [ "Office 365",             " brave --app=https://office.com/" ],
    [ "Gemini",                 " brave --app=https://gemini.google.com/" ],
    [ "Google Docs",                 " brave --app=https://docs.google.com/document/u/0/" ],
    [ "Google Sheet",                 " brave --app=https://docs.google.com/spreadsheets/u/0/" ],
    [ "Zoom Meeting",           " brave --new-window --app=https://zoom.us/id/join/" ],
    [ "Matlab",                 " brave --app=https://matlab.mathworks.com/" ],
    [ "TRanslate PDF",          " brave --new-window --app=https://onlinedoctranslator.com/" ],
    [ "Portal UNY",             " floorp --new-window --app=https://unity.uny.ac.id/" ],
    [ "Scite Ai",               " zen   --new-window --app=https://scite.ai" ],
    [ "NixOS dan Flake Book",   " zen   --new-window --app=https://nixos-and-flakes.thiscute.world" ],
    [ "EYD",                    " zen   --new-window --app=https://ejaan.kemdikbud.go.id" ],
    [ "Remaker AI",             " brave --app=https://remaker.ai/" ],
    [ "Blackbox AI",            " brave --app=https://blackbox.ai/" ],
    [ "CLaude AI",              " brave --app=https://claude.ai/" ],
    [ "Canva",                  " floorp --app=https://canva.com/" ],
    [ "HIX AI",                 " brave --app=https://hix.ai/" ],
    [ "Any Summary",            " brave --app=https://anysummary.app/" ],
    [ "JalaLive",               " brave --app=https://www.jala29.vip/" ],
    [ "Remove Object Photo",    " brave --app=https://photoroom.com/" ],
    [ "whatsapp",               " brave --app=https://web.whatsapp.com/" ],
    [ "Image Creator AI",       " brave --app=https://bing.com/images/create/" ],
    [ "Prepostseo (Parafrase)", " brave --app=https://prepostseo.com/" ],
    [ "Perplexity",             " brave --app=https://perplexity.ai/" ],
    [ "Consensus",              " brave --app=https://consensus.app/" ],
    [ "PDF tools",              " brave --app=https://iconictoolshub.com/" ],
    [ "Shortly AI",             " brave --app=https://shortlyai.com/" ],
    [ "Transcription Cockatoo", " brave --app=https://cockatoo.com/" ],
    [ "Jenni",                  " brave --app=https://jenni.ai/" ],
    [ "Open Knowledges Maps",   " brave --app=https://openknowledgemaps.org/" ],
    [ "Research rabbit",        " brave --app=https://researchrabbit.ai/" ],
    [ "Connected Paper",        " brave --app=https://connectedpapers.com/" ],
    [ "Grammarly",              " brave --app=https://grammarly.com/" ],
    [ "Yalla Shoot Live Streaming",              " brave --app=https://shotz.yalla-shoot-tv.live/home18/" ],
    [ "Humata - Review Jurnal", " brave --app=https://humata.ai/" ],
    [ "sci-hub (Open lock Journal)", " brave --app=https://sci-hub.se/" ],
    [ "Quillbot",               " brave --app=https://quillbot.com/" ],
    [ "Elicit (Ans With Journal)",   " brave --app=https://elicit.com/" ],
    [ "Bai ChatBOT",            " brave --new-window --app=https://chatbot.theb.ai/" ],
    [ "Open Asset",             " floorp --new-window --app=https://openverse.org/" ],
    [ "Scopus",                 " floorp --new-window --app=https://scopus.com/" ],
    [ "E-Book Gratis",          " floorp --new-window --app=https://libgen.is/" ],
    [ "R dan Rstudio Stat & DC", " zen --new-window --app=https://bookdown.org/aepstk/intror/" ],
    [ "Tidy Modelling W R | Program R",     " floorp --new-window --app=https://tmwr.org/" ],
    [ "Top Packages for R | Program R",     " floorp --new-window --app=https://rpubs.com/drgregmartin/1250204/" ],
    [ "Statistical ML | Program R",         " floorp --new-window --app=https://unsw-risk-and-actuarial-studies.github.io/ACTL3142/" ],
    [ "Hands On ML With R | Program R",     " floorp --new-window --app=https://bradleyboehmke.github.io/HOML/" ],
    [ "R For data science | Program R",     " floorp --new-window --app=https://r4ds.had.co.nz/" ],
    [ "Table With R | Program R",           " floorp --new-window --app=https://gt.albert-rapp.de/" ],
    [ "ezproxy UNY",            " floorp --new-window --app=https://ezproxy.uny.ac.id/" ],
    [ "Ekinerja",               " floorp --new-window --app=https://kinerja.bkn.go.id/" ],
    [ "MyAsn",                  " floorp --new-window --app=https://myasn.bkn.go.id/" ],
    [ "ASN Digital",            " floorp --new-window --app=https://asndigital.bkn.go.id/" ],
    [ "PMM",                    " floorp --new-window --app=https://guru.kemdikbud.go.id/" ],
    [ "E-Monev",                " floorp --new-window --app=https://beasiswa.kemdikbud.go.id/monev" ],
    [ "KBBI Daring",            " zen     --new-window --app=https://kbbi.kemdikbud.go.id/" ],
    [ "Scopus AI",              " zen     --new-window --app=https://www.scopus.com/search/form.uri?display=basic#scopus-ai/" ],
    [ "Siakad UNY",             " floorp --new-window --app=https://siakad.uny.ac.id/" ],
    [ "Registrasi UNY",         " floorp --new-window --app=https://registrasi.uny.ac.id/" ],
    [ "BeSmart UNY",            " floorp --new-window --app=https://besmart.uny.ac.id/" ],
    [ "E-Service UNY",          " floorp --new-window --app=https://eservice.uny.ac.id/" ],
    [ "YouTube",                " brave --app=https://youtube.com/" ],
    [ "Invidious",                " brave --app=https://inv.nadeko.net" ],
    [ "Pusdapendik",            " floorp --new-window --app=https://pusdapendik.disdik.kailinusantara.com/" ],
    [ "Gitlab",                 " floorp --new-window --app=https://gitlab.com/" ],
    [ "trello",                 " floorp --new-window --app=https://trello.com/" ],
    [ "facebook",               " brave --app=https://m.facebook.com/" ],
    [ "Instagram",              " brave --app=https://instagram.com/" ],
    [ "Elmim",             " brave --app=https://localhost" ],
    [ "Rstudio-server",             " brave --app=http://localhost:8787" ],
    [ "Excalidraw",             " brave --new-window -- app=http://localhost:5000" ],
    [ "ChatPDF",                " brave --new-window --app=http://chatpdf.com" ],
    [ "tweetDeck",              " brave --new-window --app=https://tweetdeck.twitter.com/" ],
    [ "figma",                  " brave --new-window --app=https://www.figma.com/files/drafts" ],
    [ "iptv",                   "dmenu_iptv" ],
    [ "virtual session",        "dmenu_virtualsession" ],
    [ "dns switcher",           "dmenu_dns"],
    [ "adb clipoard",           "adbclip"]
  ]
  ''''
  label=$(echo $OPTIONS | jq -r "sort | .[][0]" | $DMENU)
  exec $(echo $OPTIONS | jq -r ".[] | select(.[0] == \"$label\") | .[1]")

''
