#!/bin/bash
# File              : dmenu_mager
# License           : MIT License
# Author            : M. Nabil Adani <nblid48@gmail.com>
# Date              : Jumat, 15/05/2020 13:12 WIB
# Last Modified Date: Minggu, 11/10/2020 12:44 WIB
# Last Modified By  : M. Nabil Adani <nblid48@gmail.com>
{ pkgs }:
pkgs.writeShellScriptBin "dmenu-mager" ''
  DMENU="rofi -dmenu -i -p Mager "
  # OPTIONS = [[label, command]]
  OPTIONS=''''
  [
    [ "droidcam",               "droidcam-rofi" ],
    [ "play video0",            "mpv --no-audio --window-scale=0.5 av://v4l2:/dev/video0 --vf=hflip --profile=low-latency --untimed" ],
    [ "play video1",            "mpv --no-audio --window-scale=0.5 av://v4l2:/dev/video1 --vf=hflip --profile=low-latency --untimed" ],
    [ "play video2",            "mpv --no-audio --window-scale=0.5 av://v4l2:/dev/video2 --vf=hflip --profile=low-latency --untimed" ],
    [ "Mirror HP",              "adb-scrcpy" ],
    [ "Wifi Menu",              "rofi-network-manager" ],
    [ "Music",                  "dmenu_mpc" ],
    [ "Change Wallpaper",       "wallsetter" ],
    [ "Rofi-Wallpaper",         "rofi-wallpaper"],
    [ "Rofi-music",             "rofibeats" ],
    [ "Rofi-screnshoot",         "rofi-screenshot" ],
    [ "Rofi-Notes",             "rofi-notes" ],
    [ "Rofi-keybinds",          "keybinds" ],
    [ "Rofi-wlstream",          "rofi-wlstream" ],
    [ "Rofi-Filemanager",          "rofi-filemanager" ],
    [ "Rofi-dict",              "rofi-dict" ],
    [ "Rofi-calc",              "rofi_calc" ],
    [ "Rofi-zotero",            "rofi-zotero" ],
    [ "kill",                   "dmenu_kill" ],
    [ "kill droidcam",          "pkill droidcam-cli" ],
    [ "monitor",                "monitor-projection" ],
    [ "VOS Viewer",             "java jar ~/App/VOSviewer.jar" ],
    [ "Stop VPN",               "systemctl stop wg-quick-wg0" ],
    [ "Star VPN",               "systemctl start wg-quick-wg0" ],
    [ "Start Screen to Vcam ",  "wl-screenrec --ffmpeg-muxer v4l2 -f /dev/video0" ],
    [ "Stop Screen to Vcam ",   "pkill wl-screenrec" ],
    [ "translate-input",        "dmenu_translate -i" ],
    [ "udiskie",                "dmenu_udiskie -matching regex -dmenu -i -no-custom -multi-select -p FlashDrive" ],
    [ "Start Cloudflared",      "cloudflared tunnel run moodle" ],
    [ "Stop Cloudflared",       "pkill cloudflared" ],
    [ "umount iso",             "dmenu_iso" ],
    [ "photopea",               "uwsm app -- brave --new-window --app=https://photopea.com/" ],
    [ "Chat GPT",               "uwsm app -- brave --app=https://chat.openai.com/" ],
    [ "Google Drive",           "uwsm app -- brave --app=https://drive.google.com/" ],
    [ "Office 365",             "uwsm app -- brave --app=https://office.com/" ],
    [ "Gemini",                 "uwsm app -- brave --app=https://gemini.google.com/" ],
    [ "Zoom Meeting",           "uwsm app -- brave --new-window --app=https://zoom.us/id/join/" ],
    [ "Matlab",                 "uwsm app -- brave --app=https://matlab.mathworks.com/" ],
    [ "TRanslate PDF",          "uwsm app -- brave --new-window --app=https://onlinedoctranslator.com/" ],
    [ "Portal UNY",             "uwsm app -- floorp --new-window --app=https://unity.uny.ac.id/" ],
    [ "Scite Ai",               "uwsm app -- zen   --new-window --app=https://scite.ai" ],
    [ "NixOS dan Flake Book",   "uwsm app -- zen   --new-window --app=https://nixos-and-flakes.thiscute.world" ],
    [ "EYD",                    "uwsm app -- zen   --new-window --app=https://ejaan.kemdikbud.go.id" ],
    [ "Remaker AI",             "uwsm app -- brave --app=https://remaker.ai/" ],
    [ "Blackbox AI",            "uwsm app -- brave --app=https://blackbox.ai/" ],
    [ "CLaude AI",              "uwsm app -- brave --app=https://claude.ai/" ],
    [ "Canva",                  "uwsm app -- floorp --app=https://canva.com/" ],
    [ "HIX AI",                 "uwsm app -- brave --app=https://hix.ai/" ],
    [ "Any Summary",            "uwsm app -- brave --app=https://anysummary.app/" ],
    [ "JalaLive",               "uwsm app -- brave --app=https://www.jala29.vip/" ],
    [ "Remove Object Photo",    "uwsm app -- brave --app=https://photoroom.com/" ],
    [ "whatsapp",               "uwsm app -- brave --app=https://web.whatsapp.com/" ],
    [ "Image Creator AI",       "uwsm app -- brave --app=https://bing.com/images/create/" ],
    [ "Prepostseo (Parafrase)", "uwsm app -- brave --app=https://prepostseo.com/" ],
    [ "Perplexity",             "uwsm app -- brave --app=https://perplexity.ai/" ],
    [ "Consensus",              "uwsm app -- brave --app=https://consensus.app/" ],
    [ "PDF tools",              "uwsm app -- brave --app=https://iconictoolshub.com/" ],
    [ "Shortly AI",             "uwsm app -- brave --app=https://shortlyai.com/" ],
    [ "Transcription Cockatoo", "uwsm app -- brave --app=https://cockatoo.com/" ],
    [ "Jenni",                  "uwsm app -- brave --app=https://jenni.ai/" ],
    [ "Open Knowledges Maps",   "uwsm app -- brave --app=https://openknowledgemaps.org/" ],
    [ "Research rabbit",        "uwsm app -- brave --app=https://researchrabbit.ai/" ],
    [ "Connected Paper",        "uwsm app -- brave --app=https://connectedpapers.com/" ],
    [ "Grammarly",              "uwsm app -- brave --app=https://grammarly.com/" ],
    [ "Yalla Shoot Live Streaming",              "uwsm app -- brave --app=https://shotz.yalla-shoot-tv.live/home18/" ],
    [ "Humata - Review Jurnal", "uwsm app -- brave --app=https://humata.ai/" ],
    [ "sci-hub (Open lock Journal)", "uwsm app -- brave --app=https://sci-hub.se/" ],
    [ "Quillbot",               "uwsm app -- brave --app=https://quillbot.com/" ],
    [ "Elicit (Ans With Journal)",   "uwsm app -- brave --app=https://elicit.com/" ],
    [ "Bai ChatBOT",            "uwsm app -- brave --new-window --app=https://chatbot.theb.ai/" ],
    [ "Open Asset",             "uwsm app -- floorp --new-window --app=https://openverse.org/" ],
    [ "Scopus",                 "uwsm app -- floorp --new-window --app=https://scopus.com/" ],
    [ "E-Book Gratis",          "uwsm app -- floorp --new-window --app=https://libgen.is/" ],
    [ "R dan Rstudio Stat & DC", "uwsm app -- zen --new-window --app=https://bookdown.org/aepstk/intror/" ],
    [ "Tidy Modelling W R | Program R",     "uwsm app -- floorp --new-window --app=https://tmwr.org/" ],
    [ "Top Packages for R | Program R",     "uwsm app -- floorp --new-window --app=https://rpubs.com/drgregmartin/1250204/" ],
    [ "Statistical ML | Program R",         "uwsm app -- floorp --new-window --app=https://unsw-risk-and-actuarial-studies.github.io/ACTL3142/" ],
    [ "Hands On ML With R | Program R",     "uwsm app -- floorp --new-window --app=https://bradleyboehmke.github.io/HOML/" ],
    [ "R For data science | Program R",     "uwsm app -- floorp --new-window --app=https://r4ds.had.co.nz/" ],
    [ "Table With R | Program R",           "uwsm app -- floorp --new-window --app=https://gt.albert-rapp.de/" ],
    [ "ezproxy UNY",            "uwsm app -- floorp --new-window --app=https://ezproxy.uny.ac.id/" ],
    [ "Ekinerja",               "uwsm app -- zen --new-window --app=https://kinerja.bkn.go.id/" ],
    [ "MyAsn",                  "uwsm app -- zen --new-window --app=https://myasn.bkn.go.id/" ],
    [ "ASN Digital",            "uwsm app -- zen --new-window --app=https://asndigital.bkn.go.id/" ],
    [ "PMM",                    "uwsm app -- floorp --new-window --app=https://guru.kemdikbud.go.id/" ],
    [ "E-Monev",                "uwsm app -- floorp --new-window --app=https://beasiswa.kemdikbud.go.id/monev" ],
    [ "KBBI Daring",            "uwsm app -- zen     --new-window --app=https://kbbi.kemdikbud.go.id/" ],
    [ "Scopus AI",              "uwsm app -- zen     --new-window --app=https://www.scopus.com/search/form.uri?display=basic#scopus-ai/" ],
    [ "Siakad UNY",             "uwsm app -- floorp --new-window --app=https://siakad.uny.ac.id/" ],
    [ "Registrasi UNY",         "uwsm app -- floorp --new-window --app=https://registrasi.uny.ac.id/" ],
    [ "BeSmart UNY",            "uwsm app -- floorp --new-window --app=https://besmart.uny.ac.id/" ],
    [ "E-Service UNY",          "uwsm app -- floorp --new-window --app=https://eservice.uny.ac.id/" ],
    [ "YouTube",                "uwsm app -- brave --app=https://youtube.com/" ],
    [ "Pusdapendik",            "uwsm app -- floorp --new-window --app=https://pusdapendik.disdik.kailinusantara.com/" ],
    [ "Gitlab",                 "uwsm app -- floorp --new-window --app=https://gitlab.com/" ],
    [ "trello",                 "uwsm app -- floorp --new-window --app=https://trello.com/" ],
    [ "facebook",               "uwsm app -- brave --app=https://m.facebook.com/" ],
    [ "Instagram",              "uwsm app -- brave --app=https://instagram.com/" ],
    [ "Elmim",             "uwsm app -- brave --app=https://localhost" ],
    [ "Rstudio-server",             "uwsm app -- brave --app=http://localhost:8787" ],
    [ "Excalidraw",             "uwsm app -- brave --new-window -- app=http://localhost:5000" ],
    [ "ChatPDF",                "uwsm app -- brave --new-window --app=http://chatpdf.com" ],
    [ "tweetDeck",              "uwsm app -- brave --new-window --app=https://tweetdeck.twitter.com/" ],
    [ "figma",                  "uwsm app -- brave --new-window --app=https://www.figma.com/files/drafts" ],
    [ "iptv",                   "dmenu_iptv" ],
    [ "virtual session",        "dmenu_virtualsession" ],
    [ "dns switcher",           "dmenu_dns"],
    [ "adb clipoard",           "adbclip"]
  ]
  ''''
  label=$(echo $OPTIONS | jq -r "sort | .[][0]" | $DMENU)
  exec $(echo $OPTIONS | jq -r ".[] | select(.[0] == \"$label\") | .[1]")

''
