#!/bin/bash
# File              : dmenu_mager
# License           : MIT License
# Author            : M. Nabil Adani <nblid48@gmail.com>
# Date              : Jumat, 15/05/2020 13:12 WIB
# Last Modified Date: Minggu, 11/10/2020 12:44 WIB
# Last Modified By  : M. Nabil Adani <nblid48@gmail.com>
{ pkgs }:

pkgs.writeShellScriptBin "dmenu-mager" ''
  DMENU="rofi -dmenu -i -p Mager"
  # OPTIONS = [[label, command]]
  OPTIONS=''''
  [
    [ "boottester",             "dmenu_boottester" ],
    [ "droidcam audio only",    "droidcam-cli -a 192.168.43.1 4747 &" ],
    [ "droidcam video & audio", "droidcam-cli -a -v 192.168.43.1 4747 &" ],
    [ "droidcam video only",    "droidcam-cli 192.168.43.1 4747 &" ],
    [ "play video0",            "mpv --no-audio --window-scale=0.5 av://v4l2:/dev/video0 --vf=hflip --profile=low-latency --untimed" ],
    [ "play video1",            "mpv --no-audio --window-scale=0.5 av://v4l2:/dev/video1 --vf=hflip --profile=low-latency --untimed" ],
    [ "play video2",            "mpv --no-audio --window-scale=0.5 av://v4l2:/dev/video2 --vf=hflip --profile=low-latency --untimed" ],
    [ "kill",                   "dmenu_kill" ],
    [ "kill droidcam",          "pkill droidcam-cli" ],
    [ "monitor",                "dmenu_monitor" ],
    [ "Lumi Education",         "appimage-run ~/App/Lumi-0.10.0.AppImage" ],
    [ "Vos Veiewer",            "jar ~/App/VOSviewer.jar" ],
    [ "Fet Schedule",           "appimage-run ~/App/fet-6.25.0-x86_64.AppImage" ],
    [ "translate",              "translate" ],
    [ "mpdmenu",                "dmenu_mpdmenu" ],
    [ "Stop VPN",               "sudo systemctl stop wg-quick-wg0" ],
    [ "mpv",                    "dmenu_mpv" ],
    [ "Start Screen to Vcam ",  "wl-screenrec --ffmpeg-muxer v4l2 -f /dev/video0" ],
    [ "Stop Screen to Vcam ",   "pkill wl-screenrec" ],
    [ "pass",                   "dmenu_pass -p \"Pass Man\"" ],
    [ "power",                  "dmenu_power" ],
    [ "qutebrowser",            "dmenu_qutebrowser" ],
    [ "record",                 "dmenu_record" ],
    [ "droidapps",              "droidapps" ],
    [ "switcher",               "dmenu_switcher" ],
    [ "systemd",                "dmenu_systemd" ],
    [ "todo",                   "dmenu_todo" ],
    [ "translate-input",        "dmenu_translate -i" ],
    [ "udiskie",                "dmenu_udiskie -matching regex -dmenu -i -no-custom -multi-select -p FlashDrive" ],
    [ "wifi",                   "dmenu_wifi" ],
    [ "window",                 "dmenu_window" ],
    [ "History Command",        "history | rofi -dmenu | wl-copy" ],
    [ "youtube",                "ytfzf -fDh" ],
    [ "Start Cloudflared",      "cloudflared tunnel run moodle" ],
    [ "Stop Cloudflared",       "pkill cloudflared" ],
    [ "umount iso",             "dmenu_iso" ],
    [ "photopea",               "firefox --new-window --app=https://photopea.com/" ],
    [ "Chat GPT",               "brave --app=https://chat.openai.com/" ],
    [ "Google Drive",           "brave --app=https://drive.google.com/" ],
    [ "Office 365",             "brave --app=https://office.com/" ],
    [ "Gemini",                 "brave --app=https://gemini.google.com/" ],
    [ "Zoom Meeting",           "firefox --new-window --app=https://zoom.us/id/join/" ],
    [ "Matlab",                 "brave --app=https://matlab.mathworks.com/" ],
    [ "TRanslate PDF",          "firefox --new-window --app=https://onlinedoctranslator.com/" ],
    [ "Portal UNY",             "firefox --new-window --app=https://unity.uny.ac.id/" ],
    [ "Rstudio-server",         "brave --app=https://localhost:8787/" ],
    [ "Remaker AI",             "brave --app=https://remaker.ai/" ],
    [ "Blackbox AI",            "brave --app=https://blackbox.ai/" ],
    [ "CLaude AI",              "brave --app=https://claude.ai/" ],
    [ "Canva",                  "brave --app=https://canva.com/" ],
    [ "HIX AI",                 "brave --app=https://hix.ai/" ],
    [ "Any Summary",            "brave --app=https://anysummary.app/" ],
    [ "JalaLive",               "brave --app=https://jalalive5.com/" ],
    [ "Remove Object Photo",    "brave --app=https://photoroom.com/" ],
    [ "whatsapp",               "brave --app=https://web.whatsapp.com/" ],
    [ "Image Creator AI",       "brave --app=https://bing.com/images/create/" ],
    [ "Prepostseo (Parafrase)", "brave --app=https://prepostseo.com/" ],
    [ "Perplexity",             "brave --app=https://perplexity.ai/" ],
    [ "Consensus",              "brave --app=https://consensus.app/" ],
    [ "PDF tools",              "brave --app=https://iconictoolshub.com/" ],
    [ "Shortly AI",             "brave --app=https://shortlyai.com/" ],
    [ "Transcription Cockatoo", "brave --app=https://cockatoo.com/" ],
    [ "Jenni",                  "brave --app=https://jenni.ai/" ],
    [ "Open Knowledges Maps",   "brave --app=https://openknowledgemaps.org/" ],
    [ "Research rabbit",        "brave --app=https://researchrabbit.ai/" ],
    [ "Connected Paper",        "brave --app=https://connectedpapers.com/" ],
    [ "Grammarly",              "brave --app=https://grammarly.com/" ],
    [ "Yalla Shoot Live Streaming",              "brave --app=https://shotz.yalla-shoot-tv.live/home18/" ],
    [ "Humata - Review Jurnal", "brave --app=https://humata.ai/" ],
    [ "sci-hub (Open lock Journal)", "brave --app=https://sci-hub.se/" ],
    [ "Quillbot",               "brave --app=https://quillbot.com/" ],
    [ "Elicit (Ans With Journal)",   "brave --app=https://elicit.com/" ],
    [ "Bai ChatBOT",            "brave --app=https://chatbot.theb.ai/" ],
    [ "Open Asset",             "firefox --new-window --app=https://openverse.org/" ],
    [ "Scopus",                 "firefox --new-window --app=https://scopus.com/" ],
    [ "E-Book Gratis",          "firefox --new-window --app=https://libgen.is/" ],
    [ "Belajar R Dasar | Program R",        "firefox --new-window --app=https://bookdown.org/aepstk/intror/" ],
    [ "Tidy Modelling W R | Program R",     "firefox --new-window --app=https://tmwr.org/" ],
    [ "Statistical ML | Program R",         "firefox --new-window --app=https://unsw-risk-and-actuarial-studies.github.io/ACTL3142/" ],
    [ "Hands On ML With R | Program R",     "firefox --new-window --app=https://bradleyboehmke.github.io/HOML/" ],
    [ "R For data science | Program R",     "firefox --new-window --app=https://r4ds.had.co.nz/" ],
    [ "Table With R | Program R",           "firefox --new-window --app=https://gt.albert-rapp.de/" ],
    [ "ezproxy UNY",            "firefox --new-window --app=https://ezproxy.uny.ac.id/" ],
    [ "Ekinerja",               "firefox --new-window --app=https://kinerja.bkn.go.id/" ],
    [ "MyAsn",                  "firefox --new-window --app=https://myasn.bkn.go.id/" ],
    [ "PMM",                    "firefox --new-window --app=https://guru.kemdikbud.go.id/" ],
    [ "E-Monev",                "firefox --new-window --app=https://beasiswa.kemdikbud.go.id/monev" ],
    [ "Siakad UNY",             "firefox --new-window --app=https://siakad.uny.ac.id/" ],
    [ "Registrasi UNY",         "firefox --new-window --app=https://registrasi.uny.ac.id/" ],
    [ "BeSmart UNY",            "firefox --new-window --app=https://besmart.uny.ac.id/" ],
    [ "E-Service UNY",          "firefox --new-window --app=https://eservice.uny.ac.id/" ],
    [ "YouTube",                "brave --app=https://youtube.com/" ],
    [ "Pusdapendik",            "firefox --new-window --app=https://pusdapendik.disdik.kailinusantara.com/" ],
    [ "Gitlab",                 "firefox --new-window --app=https://gitlab.com/" ],
    [ "trello",                 "firefox --new-window --app=https://trello.com/" ],
    [ "facebook",               "brave --app=https://m.facebook.com/" ],
    [ "E-Learning",             "brave --app=https://localhost" ],
    [ "Excalidraw",             "brave --app=http://localhost:5000" ],
    [ "ChatPDF",                "brave --app=http://chatpdf.com" ],
    [ "tweetDeck",              "firefox --new-window --app=https://tweetdeck.twitter.com/" ],
    [ "figma",                  "firefox --new-window --app=https://www.figma.com/files/drafts" ],
    [ "iptv",                   "dmenu_iptv" ],
    [ "dmenu_ffmpeg",           "dmenu_ffmpeg" ],
    [ "dmenu_aria",             "dmenu_aria" ],
    [ "rofi-calc",              "roi-calc" ],
    [ "virtual session",        "dmenu_virtualsession" ],
    [ "dns switcher",           "dmenu_dns"],
    [ "adb clipoard",           "adbclip"]
  ]
  ''''
  label=$(echo $OPTIONS | jq -r "sort | .[][0]" | $DMENU)
  exec $(echo $OPTIONS | jq -r ".[] | select(.[0] == \"$label\") | .[1]")

''
