{ pkgs, config, lib, ... }:
}
  environment.systemPackages = with pkgs; let
          list-packages = with rPackages; [
            quarto
            AER
            Amelia
            AmesHousing
            BB
            BBmisc
            BH
            BatchJobs
            BiasedUrn
            BoolNet
            BradleyTerry2
            Brobdingnag
            CVST
            Cairo
            CircStats
           #ClustVarLV
           #Cubist
           #DAAG
           #DBI
           #DBItest
           #DEoptim
           #DEoptimR
           #DRR
           #DT
           #DendSer
           #Deriv
           #DescTools
           #DistributionUtils
           #DoseFinding
           #EnvStats
           #FMStable
           #FNN
           #Fahrmeir
           #Formula
           #GGally
           #GPArotation
           #GeneralizedHyperbolic
           #GlobalOptions
           #HistData
           #Hmisc
           #ICEbox
           #ICS
           #ICSNP
           #IRdisplay
           #IRkernel
           #ISOcodes
           #ISwR
           #Iso
           #JM
           #JuliaCall
           #JuliaConnectoR
           #KernSmooth
           #Lahman
           #LearnBayes
           #Luminescence
           #MALDIquant
           #MCMCpack
           #MLmetrics
           #MNP
           #MatchIt
           #Matching
           #MatrixModels
           #ModelMetrics
           #NADA
           #NLP
           #NMF
           #NMOF
           #PKI
           #PerformanceAnalytics
           #R2HTML
           #R2WinBUGS
           #R2jags
           #R6
           #RANN
           #RClickhouse
           #RColorBrewer
           #RCurl
           #RInside
           #RJSONIO
           #RNeXML
           #ROCR
           #RSQLite
           #RSclient
           #RUnit
           #RaschSampler
           #Rcgmin
           #RcmdrMisc
           #Rcpp
           #RcppArmadillo
           #RcppEigen
           #RcppProgress
           #RcppRoll
           #Rdpack
           #Rmpfr
           #Rmpi
           #Rserve
           #Rsolnp
           #Rtsne
           #Rvmmin
           #SGP
           #SGPdata
           #Sleuth2
           #SnowballC
           #StanHeaders
           #SuppDists
           #TH_data
           #TRAMPR
           #TSP
           #TTR
           #TeachingDemos
           #Unicode
           #VGAM
           #VGAMdata
           #VIM
           #WDI
           WikidataR
           WikipediR
           #XML
           #abind
           #acepack
           #actuar
           #ade4
           #adegenet
           #adegraphics
           #adephylo
           #afex
           #analogue
           #animation
           #ape
           #argparse
           #arm
           #ash
           #askpass
           #assertthat
           #backports
           #base64enc
           #bayesm
           #bayesplot
           #bazar
           #bbmle
           #bdsmatrix
           #beeswarm
           #benchr
           #betareg
           #bibtex
           #biglm
           #binGroup
            bindr
           #bindrcpp
           #bio3d
           #bipartite
           #bit
           #bit64
           #bitops
           #blob
           #blockmodeling
           #blogdown
           #bold
           #bootstrap
           #brew
           #brglm
           #bridgesampling
           #brms
           #broom
           #bvls
           #ca
           #caTools
           #calibrate
           #calibrator
           #callr
           #car
           #carData
           #caret
           #cclust
           #cellranger
           #checkmate
           #chron
           #circlize
           #classInt
           #cli
           #clipr
           #clisymbols
           #clue
           #clustMixType
           #clusterGeneration
           #cmprsk
           #cobs
           #coda
           #codetools
           #coin
           #colorspace
           #colourpicker
           #combinat
           #commonmark
           #compositions
           #contfrac
           #corpcor
           #corrgram
           #corrplot
           #covr
           #cowplot
           #crayon
           #crosstalk
           #crul
           #csvy
           #cubature
           #curl
           #cvTools
           #cyclocomp
           #data_table
           #date
           #dbarts
           #dbplyr
           #dcurver
           #ddalpha
           #debugme
           #deepnet
           #deldir
           #dendextend
           #desc
           #devtools
           #dfoptim
           #dichromat
           #diffobj
           #diffusionMap
           #digest
           #dimRed
           #diptest
           #distr
           #distrEx
           #dlm
           #doMC
           #doParallel
           #doRNG
           #doSNOW
           #dotCall64
           #downloader
           #dplyr
           #drc
           #dtplyr
           #dtw
           #dygraphs
           #dynlm
           #e1071
           #eRm
           #earth
           #eha
           #eiPack
           #ellipse
           #ellipsis
           #elliptic
           #emmeans
           #emulator
           #enc
           #energy
           #epiR
           #epibasix
           #epitools
           #equate
           #estimability
           #etm
           #evaluate
           #evd
           #expint
           #expm
           #expsmooth
           #fAssets
           #fBasics
           #fBonds
           #fCopulae
           #fExtremes
           #fGarch
           #fImport
           #fMultivar
           #fNonlinear
           #fRegression
           #fTrading
           #fUnitRoots
           #fail
           #fansi
           #fastICA
           #fastcluster
           #fastmap
           #fastmatch
           #fauxpas
           #feather
           #ff
           #fields
           #filehash
           #findpython
           #fit_models
           #fitbitScraper
           #fitdistrplus
           #flashClust
           #flexmix
           #fontBitstreamVera
           #fontLiberation
           #fontquiver
           #forcats
           #foreach
           #forecast
           #formatR
           #fossil
           #fpc
           #fracdiff
           #fs
           #fst
           #furrr
           #futile_logger
           #futile_options
           #future
           #g_data
           #gam
           #gamm4
           #gbRd
           #gbm
           #gbutils
           #gclus
           #gdata
           #gdtools
           #geepack
           #generics
           #geojson
           #geometry
           #getopt
           #ggjoy
           #ggplot2
           #ggplot2movies
           #ggridges
           #ggvis
           #gh
           #git2r
           #glmnet
           #globals
           #glue
           #gmodels
           #gmp
           #gnm
           #goftest
           #googleVis
           #gower
           #gplots
           #gridBase
           #gridExtra
           #gss
           #gtable
           #gtools
           #haplo_stats
           #haven
           #hdrcde
           #here
           #hexView
           #hexbin
           #highlight
           #highr
           #hms
           #htmlTable
           #htmltools
           #htmlwidgets
           #httpcode
           #httpuv
           #httr
           #hunspell
           #hwriter
           #ica
           #igraph
           #ineq
           #influenceR
           #ini
           #inline
           #inum
           #invgamma
           #ipred
           #irlba
           #iterators
           #janitor
           #joineR
           #joineRML
           #jpeg
           #jqr
           #jsonlite
           #keras
           #kernlab
           #kimisc
           #klaR
           #kmi
           #knitr
           #ks
           #labeling
           #labelled
           #laeken
           #lambda_r
           #languageR
           #languageserver
           #lars
           #later
           #latticeExtra
           #lava
           #lavaan
           #lazyeval
           #lda
           #leaflet
           #leaps
           #learnr
           #lfe
           #lhs
           #libcoin
           #lifecycle
           #lightgbm
           #linprog
           #lintr
           #listenv
           #listviewer
           #lme4
           #lmerTest
           #lmtest
           #locfit
           #logcondens
           #logspline
           #loo
           #lpSolve
           #lsei
           #lsmeans
           #lubridate
           #luz
           #lwgeom
           #mFilter
           #magic
           #magick
           #magrittr
           #manipulate
           #manipulateWidget
           #mapdata
           #mapproj
           #maps
           #matrixStats
           #matrixcalc
           #maxLik
           #mclust
           #mcmc
           #mda
           #measures
           #memisc
           #memoise
           #mi
           #microbenchmark
           #mime
           #miniUI
           #minpack_lm
           #minqa
           #mirt
           #misc3d
           #miscF
           #miscTools
           #mitools
           #mixtools
           #mlbench
           #mlmRev
           #mnormt
           #mockery
           #mockr
           #modelr
           #modeltime
           #modeltools
           #modest
           #mondate
           #mongolite
           #msm
           #mstate
           #muhaz
           #multcomp
           #multcompView
           #multicool
           #multiwayvcov
           #munsell
           #mvnfast
           #mvnormtest
           #mvoutlier
           #mvtnorm
           #natserv
           #ncbit
           #ncdf4
           #network
           #networkR
           #neuralnet
           #nleqslv
           #nloptr
           #nnls
           #nortest
           #npsurv
           #numDeriv
           #nycflights13
           #odbc
           #openssl
           #openxlsx
           #optextras
           #optimx
           #optparse
           #ordinal
           #packrat
           #pamr
           #parsedate
           #partitions
           #party
           #partykit
           #pbapply
           #pbdZMQ
           #pbivnorm
           #pbkrtest
           #pbmcapply
           #pcaPP
           #pcse
           #pdfCluster
           #pdftools
           #pdp
           #permute
           #phangorn
           #pheatmap
           #phylobase
           #phylogram
           #phytools
           #pillar
           #pkgKitten
           #pkgbuild
           #pkgconfig
           #pkgdown
           #pkgload
           #pkgmaker
           #plm
           #plogr
           #plotly
           #plotmo
           #plyr
           #pmml
           #png
           #poLCA
           #polspline
           #polyCub
           #polyclip
           #polycor
           #polynom
           #prabclus
           #pracma
           #praise
           #prefmod
           #prettyunits
           #princurve
           #processx
           #prodlim
           #profileModel
           #progress
           #promises
           #prophet
           #proto
           #protolite
           #proxy
           #pryr
           #ps
           #pscl
           #psy
           #psych
           #psychotools
           #purrr
           #pvclust
           #pwt
           #pwt8
           #pxweb
           #qap
           #qpdf
           #qqman
           #qtl
           #quadprog
           #quantmod
           #quantreg
           #quarto
           #questionr
           #qvcalc
           #randomForest
           #randomNames
           #randtests
           #randtoolbox
            ranger
            rappdirs
            raster
            rasterVis
            rbenchmark
            rbokeh
            rcmdcheck
            reactR
            reactlog
            readODS
            readr
            readstata13
            readxl
            recipes
           #registry
           #relimp
           #rematch
           #rematch2
           #remote
           #remotes
           #rentrez
           #repr
           #reprex
           #reshape
           #reshape2
           #reticulate
           #rex
           #rgenoud
           #rgl
           #rglwidget
           #rhandsontable
           #rhub
           #rio
           #ritis
           #rjags
           #rjstat
           #rlang
           #rmarkdown
           #rms
           #rmutil
           #rncl
           #rneos
           #rngWELL
           #rngtools
           #robust
           #robustbase
           #rootSolve
           #rotl
           #roxygen2
           #rprojroot
           #rrcov
           #rredlist
           #rsample
           #rsconnect
           #rsdmx
           #rstan
           #rstanarm
           #rstantools
           #rstudioapi
           #rsvg
           #runjags
           #rversions
           #rvest
           #sampling
           #sandwich
           #scales
           #scatterplot3d
           #segmented
           #selectr
           #sem
           #sendmailR
           #seqinr
           #seriation
           #sessioninfo
           #setRNG
           #sf
           #sfsmisc
           #sgeostat
           #shape
           #shapefiles
           #shiny
           #shinyBS
           #shinydashboard
           #shinyjs
           #shinystan
           #shinythemes
           #slam
           #sm
           #smoother
           #sn
           #sna
           #snakecase
           #snow
           #snowfall
           #solrium
           #som
           #sourcetools
           #sp
           #spData
           #spam
           #spatstat
           #spatstat_data
           #spatstat_utils
           #spc
           #spdep
           #spelling
           #spls
           #stable
           #stabledist
           #startupmsg
           #statip
           #statmod
           #statnet_common
           #stringdist
           #stringi
           #stringr
           #strucchange
           #styler
           #subplex
           #subselect
           #superpc
           #survey
           #svUnit
           #sys
           #systemfit
           #systemfonts
           #tau
           #taxize
           #tclust
           #tensor
           #tensorA
           #tensorflow
           #testit
           #testthat
           #texreg
           #tfruns
           #threejs
           #tibble
            tidyselect
            tidyverse
            timeDate
            timeSeries
            tinytex
            tis
           #tm
           #toOrdinal
           #topicmodels
           #torch
           #torchdatasets
           #torchvision
           #tree
           #triebeard
           #trimcluster
           #truncdist
           #truncnorm
           #tseries
           #tsne
           #ucminf
           #udpipe
           #units
           #unix
           #urca
           #urltools
           #uroot
           #usethis
           #utf8
           #uuid
           #varImp
           #vcd
           #vcdExtra
           #vcr
           #vctrs
           #vegan
           #vioplot
           #viridis
           #viridisLite
           #visNetwork
           #webmockr
           #webshot
           #webutils
           #whisker
           #whoami
           #wikitaxa
           #withr
           #worrms
            xfun
            xml2
            xmlparsedata
            xopen
           #xtable
           #xts
           #yaml
           #zCompositions
           #zeallot
           #zip
           #zoo
          ];
          r-with-packages =
          (
            rWrapper.override {
              packages = list-packages;
            }
          );
          rstudio-with-packages =
          (
            rstudioWrapper.override {
              packages = list-packages;
            }
          );
        in [
          r-with-packages
          rstudio-with-packages
        ];

}
