[pyprland]
plugins = [
  "scratchpads",
  "magnify",
  "expose",
]

[scratchpads.term]
command = "kitty --class kitty-dropterm"
animation = "fromTop"
class = "kitty-dropterm"
size ="75% 60%"
unfocus = "hide"
excludes = "*"
lazy = true

[scratchpads.volume]
command = "pavucontrol --class volume_sidemenu"
animation = "fromRight"
class = "volume_sidemenu"
size = "40% 70%"
unfocus = "hide"
excludes = "*"
lazy = true
