{ pkgs, config, lib, inputs, ... }:

let
  inherit (import ../../../options.nix)
    browser
    terminal
    sdl-videodriver;
in with lib; {
  wayland.windowManager.hyprland.settings = {
    bind =[
      "$mod ,Q,exec,${terminal} -e fish"
      "$mod ,RETURN,exec,kitty"
      "$mod ,A,exec,rofi-launcher"
      "$mod SHIFT,W,exec,web-search"
      "$mod SHIFT,F,exec,rofi -show filebrowser"
      "$mod SHIFT,S,exec,swaync-client -rs"
	    "$mod ,W,exec,[workspace 2 silent]${browser}"
      "$mod , minus, movetoworkspace,special"
      "$mod , equal, togglespecialworkspace"
      "$mod SHIFT,M,exec,emopicker9000"
      "$mod ,N,exec,joplin-desktop"
      "$mod CONTROL,N,exec, kitty -e joplin --profile ~/.config/joplin-desktop"
      "$mod ,S,exec,screenshootin"
      "$mod ,D,exec,discord"
      "$mod ,R,exec,libreoffice --writer"
      "$mod ,C,exec,libreoffice --calc"
      "$mod ,T,exec,[workspace 9 silent] telegram-desktop"
      "$mod ,K,exec, rofi -show calc -modi calc -no-show-match -no-sort"
      "$mod ,B,exec, rofi-bluetooth"
      "$mod ,Y,exec, kitty -e ytfzf -t --thumb-viewer=kitty"
      "$mod ,I,exec,${terminal} -e syncthing"
      "$mod ,O,exec,obs"
      "$mod ,G,exec,gimp"
      "$mod SHIFT,G,exec, fish -c record_scree_gif"
      "$mod ,E,exec,thunar"
      "$mod ,TAB,exec,rofi -show window -window-thumbnail"
      "$mod SHIFT,E,exec,kitty -e yazi"
      "$mod SHIFT,Y,exec,spotify"
      "$mod ,X,killactive,"
      "$mod SHIFT,K,exec, kitty -e lvim ~/hyprnix/config/home/hyprland.nix"
      "$mod ,P,pseudo,"
      "$mod CONTROL,P,exec,monitor-projection"
      "$mod ,Z,exec, rofi -show power-menu -modi power-menu:rofi-power-menu"
      "$mod SHIFT,I,togglesplit,"
      "$mod ,F,fullscreen,"
      "$mod ,V,exec,cliphist list | rofi -dmenu | cliphist decode | wl-copy"
      "$mod ,Space,togglefloating,"
      "$mod SHIFT,P,exec, hyprpicker --autocopy"
      "$mod SHIFT,C,exec, rofi-calc"
      "$mod SHIFT,Z,exec, pypr zoom"
      "$mod SHIFT,A,exec, pypr expose"
      "$mod SHIFT,RETURN,exec, pypr toggle term"
      "$mod CONTROL,C,exec,pypr toggle calendar"
      "$mod ALT,N,exec, wifi-menu"
      "CONTROL, TAB,focuscurrentorlast"
      "$mod SHIFT,N,exec, sh ~/hyprnix/config/home/files/dmenu_iptv"
      "$mod SHIFT,left,movewindow,l"
      "$mod SHIFT,right,movewindow,r"
      "$mod SHIFT,up,movewindow,u"
      "$mod SHIFT,down,movewindow,d"
      "$mod SHIFT,h,movewindow,l"
      "$mod SHIFT,l,movewindow,r"
      "$mod SHIFT,k,movewindow,u"
      "$mod SHIFT,j,movewindow,d"
      "$mod SHIFT,R,exec,pkill wf-recorder"
      "$mod ,M,exec,dmenu-mager"
      "$mod SHIFT,S,exec,rofi-pulse-select sink"
      "$mod CONTROL,R,exec,wf-recorder -c h264_vaapi -g $(slurp) --audio --file=$HOME/Videos/$(date +Rec%d%m%Y_%Hh%Mm%Ss.mp4)"
      "$mod ALT,S,exec,rofi-pulse-select source"
      "$mod ALT,R,exec,wf-recorder --audio --file=$HOME/videos/$(date +Rec%d%m%Y_%Hh%Mm%Ss.mp4)"
      "$mod CONTROL,X,exec,wf-recorder -c h264_vaapi --muxer=v4l2 --codec=rawvideo --file=/dev/video2 -x yuv420p"
      "$mod ,left,movefocus,l"
      "$mod ,right,movefocus,r"
      "$mod ,up,movefocus,u"
      "$mod ,down,movefocus,d"
      "$mod SHIFT,U,exec,rofi -show find -modi find:rofi-finder"
      "$mod ,U,exec,rofi -show recursivebrowser -theme-str 'window {width: 80%; height: 60%;}'"
      ",Print,exec,grim"
      "$mod ,print,exec, sattyss"
      "$mod SHIFT,O,exec, ocr-screenshot"
      "$mod SHIFT,T,exec, ocr-indonesia"
      "$mod ALT, T, exec,terjemah"
      "$mod ,BACKSLASH,exec, hyprctl dispatch splitratio 0.3"
      "$mod SHIFT, G, togglegroup # toggle group"
      "$mod SHIFT, H, changegroupactive  # change focus to another window"
      "$mod ,h,movefocus,l"
      "$mod ,l,movefocus,r"
      "$mod ,k,movefocus,u"
      "$mod ,j,movefocus,d"
      "$mod ,1,workspace,1"
      "$mod ,2,workspace,2"
      "$mod ,3,workspace,3"
      "$mod ,4,workspace,4"
      "$mod ,5,workspace,5"
      "$mod ,6,workspace,6"
      "$mod ,7,workspace,7"
      "$mod ,8,workspace,8"
      "$mod ,9,workspace,9"
      "$mod ,0,workspace,10"
      "$mod CONTROL,1,workspace,11"
      "$mod CONTROL,2,workspace,12"
      "$mod CONTROL,3,workspace,13"
      "$mod CONTROL,4,workspace,14"
      "$mod CONTROL,5,workspace,15"
      "$mod CONTROL,6,workspace,16"
      "$mod CONTROL,7,workspace,17"
      "$mod CONTROL,8,workspace,18"
      "$mod CONTROL,9,workspace,19"
      "$mod CONTROL,0,workspace,20"
      "ALT,1,movetoworkspace,1"
      "ALT,2,movetoworkspace,2"
      "ALT,3,movetoworkspace,3"
      "ALT,4,movetoworkspace,4"
      "ALT,5,movetoworkspace,5"
      "ALT,6,movetoworkspace,6"
      "ALT,7,movetoworkspace,7"
      "ALT,8,movetoworkspace,8"
      "ALT,9,movetoworkspace,9"
      "ALT,0,movetoworkspace,10"
      "CONTROLALT,1,movetoworkspace,11 "
      "CONTROLALT,2,movetoworkspace,12 "
      "CONTROLALT,3,movetoworkspace,13"
      "CONTROLALT,4,movetoworkspace,14"
      "CONTROLALT,5,movetoworkspace,15"
      "CONTROLALT,6,movetoworkspace,16"
      "CONTROLALT,7,movetoworkspace,17"
      "CONTROLALT,8,movetoworkspace,18"
      "CONTROLALT,9,movetoworkspace,19"
      "CONTROLALT,0,movetoworkspace,20"
      "$mod SHIFT,1,movetoworkspacesilent,1"
      "$mod SHIFT,2,movetoworkspacesilent,2"
      "$mod SHIFT,3,movetoworkspacesilent,3"
      "$mod SHIFT,4,movetoworkspacesilent,4"
      "$mod SHIFT,5,movetoworkspacesilent,5"
      "$mod SHIFT,6,movetoworkspacesilent,6"
      "$mod SHIFT,7,movetoworkspacesilent,7"
      "$mod SHIFT,8,movetoworkspacesilent,8"
      "$mod SHIFT,9,movetoworkspacesilent,9"
      "$mod SHIFT,0,movetoworkspacesilent,10"
      "$mod ALT,X,exec,hyprctl reload"
      "$mod CONTROL,right,workspace,e+1"
      "$mod CONTROL,left,workspace,e-1"
      "$mod ,mouse_down,workspace, e+1"
      "$mod ,mouse_up,workspace, e-1"
      "$mod ALT,right, resizeactive, 30 0"
      "$mod ALT,left, resizeactive, -30 0"
      "$mod ,SLASH,exec, hyprctl dispatch pin"
      "$mod ALT,SLASH,exec, hyprctl dispatch unset"
      "ALT,Tab,cyclenext"
      "ALT,Tab,bringactivetotop"
      ",XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ",XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      ",XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ",XF86MonBrightnessDown,exec,brightnessctl set 5%-"
      ",XF86MonBrightnessUp,exec,brightnessctl set +5%"
      "$mod , grave,exec,hyprexpo:expo, toggle "
      # " Monitor"
      "$mod CONTROL,PERIOD,exec, hyprctl --batch 'keyword monitor eDP-1,highres,0x0,1; keyword monitor HDMI-A-1,1920x1080,1920x0,1'"
      "$mod CONTROL,COMMA, exec, hyprctl --batch 'keyword monitor HDMI-A-1,1920x1080,0x0,1; keyword monitor eDP-1,highres,1920x0,1'"
      "$mod CONTROL,m, exec, hyprctl --batch 'keyword monitor eDP-1,highres,0x0,1;keyword monitor HDMI-A-1,1920x1080,0x0,1,mirror,eDP-1'"
      "$mod CONTROL,d, exec, hyprctl --batch 'keyword monitor HDMI-A-1,1920x1080,1920x0,1;' && sleep 1 && hyprctl --batch 'keyword monitor eDP-1,disable'"
      "$mod CONTROL,SPACE, exec, hyprctl --batch 'keyword monitor eDP-1,highres,0x0,1; keyword monitor HDMI-A-1,disable'"
      # "layout"
      "$mod ALT, m, exec, hyprctl --batch 'keyword general:layout master'"
      "$mod ALT, d, exec, hyprctl --batch 'keyword general:layout dwindle'"
      "$mod SHIFT, B, exec, hyprctl getoption plugin:hyprbars:nobar"
      "$mod ,F4,pass,^(com\.obsproject\.Studio)$"
      "$mod ,F5,pass,^(com\.obsproject\.Studio)$"
      "$mod ,F6,pass,^(com\.obsproject\.Studio)$"
      "$mod ,F7,pass,^(com\.obsproject\.Studio)$"
      "$mod ,F10,pass,^(com\.obsproject\.Studio)$"
      "$mod ,F8,pass,^(com\.obsproject\.Studio)$"
      "$mod ,F9,pass,^(com\.obsproject\.Studio)$"
      "$mod ,RBRACKET,pass,^(com\.obsproject\.Studio)$"
      "$mod ,APOSTROPHE,pass,^(com\.obsproject\.Studio)$"
      "$mod ,LBRACKET,pass,^(com\.obsproject\.Studio)$"
      "$mod ,SEMICOLON,pass,^(com\.obsproject\.Studio)$"
      "$mod ,comma,pass,^(com\.obsproject\.Studio)$"
      "$mod ,period,pass,^(com\.obsproject\.Studio)$"

      ];


    bindm = [
      "$mod ,mouse:272,movewindow"
      "$mod ,mouse:273,resizewindow"
      ];
  };

}
